# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
#get data from csv file
df=pd.read_csv('global-coal-plant-tracker.csv')
df

,UNIT,PLANT,PARENT,URL,SPONSOR,CAPACITY_MW,STATUS,REGION,COUNTRY,SUBNATIONAL_UNIT,GEOPOINT
0,Unit 1,RÃ­o Turbio Power Station,Yacimientos CarbonÃ­feros De RÃ­o Turbio Sa,https://www.gem.wiki/R%C3%ADo_Turbio_power_sta...,NaN,120.0,Operating,Americas,Argentina,Santa Cruz,-51.54601
1,Unit 2,RÃ­o Turbio Power Station,Yacimientos CarbonÃ­feros De RÃ­o Turbio Sa,https://www.gem.wiki/R%C3%ADo_Turbio_power_sta...,NaN,120.0,Construction,Americas,Argentina,Santa Cruz,-51.54601
2,Unit 1,Anglesea Power Station,Alcoa Corp,https://www.gem.wiki/Anglesea_power_station,NaN,160.0,Retired,Oceania,Australia,Victoria,-38.38655
3,Unit 2,Bluewaters Power Station,Kansai Electric Power Co; Sumitomo Corp,https://www.gem.wiki/Bluewaters_power_station,NaN,233.0,Operating,Oceania,Australia,Western Australia,-33.33219
4,Unit 1,Collinsville Power Station,Ratch Group Plc,https://www.gem.wiki/Collinsville_power_station,NaN,30.0,Retired,Oceania,Australia,Queensland,-20.54505
...,...,...,...,...,...,...,...,...,...,...,...
13779,Unit 5,Sengwa Power Station,Riozim,https://www.gem.wiki/Sengwa_power_station,NaN,350.0,Announced,Africa,Zimbabwe,Midlands,-18.22000
13780,Unit 8,Sengwa Power Station,Riozim,https://www.gem.wiki/Sengwa_power_station,NaN,350.0,Announced,Africa,Zimbabwe,Midlands,-18.22000
13781,Unit 2,Western Coal And Energy Power Station,Western Coal And Energy Company,https://www.gem.wiki/Western_Coal_and_Energy_p...,NaN,300.0,Shelved,Africa,Zimbabwe,Matabeleland North,-17.83333
13782,Unit 3,Zhongxin Power Station,Yuxia Zhongxin Coking Co,https://www.gem.wiki/ZhongXin_power_station,NaN,135.0,Construction,Africa,Zimbabwe,Matabeleland North,-18.08277
13783,NaN,Zimbabwe Power Station,China Railway International; Zesa Holdings Ltd,https://www.gem.wiki/Zimbabwe_power_station,NaN,1200.0,Cancelled,Africa,Zimbabwe,Unknown,-19.01692

In [3]:
#health check for data 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13784 entries, 0 to 13783
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   UNIT              13133 non-null  str
 1   PLANT             11405 non-null  str
 2   PARENT            11401 non-null  str
 3   URL               11324 non-null  str
 4   SPONSOR           0 non-null      float64
 5   CAPACITY_MW       11324 non-null  float64
 6   STATUS            11324 non-null  str
 7   REGION            11324 non-null  str
 8   COUNTRY           11324 non-null  str
 9   SUBNATIONAL_UNIT  11321 non-null  str
 10  GEOPOINT          11324 non-null  float64
dtypes: float64(3), str(8)
memory usage: 2.9 MB

In [4]:
#check sumarry statistics of data
df.describe().round()

       SPONSOR  CAPACITY_MW  GEOPOINT
count      0.0      11324.0   11324.0
mean       NaN        345.0      30.0
std        NaN        370.0      18.0
min        NaN         30.0     -52.0
25%        NaN        100.0      23.0
50%        NaN        230.0      35.0
75%        NaN        572.0      42.0
max        NaN       6300.0      70.0

In [5]:
#get summary for categorigal data
df.describe(include=['object','string'])

,UNIT,PLANT,PARENT,URL,STATUS,REGION,COUNTRY,SUBNATIONAL_UNIT
count,13133,11405,11401,11324,11324,11324,11324,11321
unique,478,4242,2414,4211,9,5,105,720
top,Unit 1,Pukchang Power Station,Ntpc Ltd,https://www.gem.wiki/Pukchang_power_station,Operating,Asia,China,Shandong
freq,2772,20,185,20,5198,7585,3728,491

In [6]:
#convert for new data type
df = df.convert_dtypes()

In [7]:
#convert columns name to lower case
df.columns = df.columns.str.lower()
df.columns

Index(['unit', 'plant', 'parent', 'url', 'sponsor', 'capacity_mw', 'status',
       'region', 'country', 'subnational_unit', 'geopoint'],
      dtype='str')

In [8]:
#check for dublicate data
df.duplicated().sum()

np.int64(2341)

In [9]:
#show duplicated data
df[df.duplicated()]

,unit,plant,parent,url,sponsor,capacity_mw,status,region,country,subnational_unit,geopoint
33,Phase I,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
34,Phase I,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
125,Phase I,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
126,Phase I,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
129,Phase Ii,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...
13065,Phase I,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
13153,Phase 3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
13154,Phase 2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
13155,Phase 3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
13156,Phase 3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [10]:
#drop duplicated data
df = df.drop_duplicates()

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
#check for missing values
df.isna().sum()

unit                  651
plant                  38
parent                 42
url                   119
sponsor             11443
capacity_mw           119
status                119
region                119
country               119
subnational_unit      122
geopoint              119
dtype: int64

In [13]:
#check missing vlaues %
df.isna().mean().round(4)*100

unit                  5.69
plant                 0.33
parent                0.37
url                   1.04
sponsor             100.00
capacity_mw           1.04
status                1.04
region                1.04
country               1.04
subnational_unit      1.07
geopoint              1.04
dtype: float64

In [14]:
# Data Cleaning

In [15]:
#handle missing values
df.drop(columns=['sponsor'],inplace=True)

In [16]:
#handle missing values in other columns
df = df.dropna(subset=['url','capacity_mw','status','region','country','geopoint'])

In [17]:
df

,unit,plant,parent,url,capacity_mw,status,region,country,subnational_unit,geopoint
0,Unit 1,RÃ­o Turbio Power Station,Yacimientos CarbonÃ­feros De RÃ­o Turbio Sa,https://www.gem.wiki/R%C3%ADo_Turbio_power_sta...,120,Operating,Americas,Argentina,Santa Cruz,-51.54601
1,Unit 2,RÃ­o Turbio Power Station,Yacimientos CarbonÃ­feros De RÃ­o Turbio Sa,https://www.gem.wiki/R%C3%ADo_Turbio_power_sta...,120,Construction,Americas,Argentina,Santa Cruz,-51.54601
2,Unit 1,Anglesea Power Station,Alcoa Corp,https://www.gem.wiki/Anglesea_power_station,160,Retired,Oceania,Australia,Victoria,-38.38655
3,Unit 2,Bluewaters Power Station,Kansai Electric Power Co; Sumitomo Corp,https://www.gem.wiki/Bluewaters_power_station,233,Operating,Oceania,Australia,Western Australia,-33.33219
4,Unit 1,Collinsville Power Station,Ratch Group Plc,https://www.gem.wiki/Collinsville_power_station,30,Retired,Oceania,Australia,Queensland,-20.54505
...,...,...,...,...,...,...,...,...,...,...
13779,Unit 5,Sengwa Power Station,Riozim,https://www.gem.wiki/Sengwa_power_station,350,Announced,Africa,Zimbabwe,Midlands,-18.22
13780,Unit 8,Sengwa Power Station,Riozim,https://www.gem.wiki/Sengwa_power_station,350,Announced,Africa,Zimbabwe,Midlands,-18.22
13781,Unit 2,Western Coal And Energy Power Station,Western Coal And Energy Company,https://www.gem.wiki/Western_Coal_and_Energy_p...,300,Shelved,Africa,Zimbabwe,Matabeleland North,-17.83333
13782,Unit 3,Zhongxin Power Station,Yuxia Zhongxin Coking Co,https://www.gem.wiki/ZhongXin_power_station,135,Construction,Africa,Zimbabwe,Matabeleland North,-18.08277
13783,<NA>,Zimbabwe Power Station,China Railway International; Zesa Holdings Ltd,https://www.gem.wiki/Zimbabwe_power_station,1200,Cancelled,Africa,Zimbabwe,Unknown,-19.01692

In [18]:
df.reset_index(inplace= True, drop= True)

In [19]:
df.head()

,unit,plant,parent,url,capacity_mw,status,region,country,subnational_unit,geopoint
0,Unit 1,RÃ­o Turbio Power Station,Yacimientos CarbonÃ­feros De RÃ­o Turbio Sa,https://www.gem.wiki/R%C3%ADo_Turbio_power_sta...,120,Operating,Americas,Argentina,Santa Cruz,-51.54601
1,Unit 2,RÃ­o Turbio Power Station,Yacimientos CarbonÃ­feros De RÃ­o Turbio Sa,https://www.gem.wiki/R%C3%ADo_Turbio_power_sta...,120,Construction,Americas,Argentina,Santa Cruz,-51.54601
2,Unit 1,Anglesea Power Station,Alcoa Corp,https://www.gem.wiki/Anglesea_power_station,160,Retired,Oceania,Australia,Victoria,-38.38655
3,Unit 2,Bluewaters Power Station,Kansai Electric Power Co; Sumitomo Corp,https://www.gem.wiki/Bluewaters_power_station,233,Operating,Oceania,Australia,Western Australia,-33.33219
4,Unit 1,Collinsville Power Station,Ratch Group Plc,https://www.gem.wiki/Collinsville_power_station,30,Retired,Oceania,Australia,Queensland,-20.54505

In [20]:
#check outliers
px.box(df, y='capacity_mw', title='Box Plot of Capacity (MW)')

In [21]:
num_cols=df.select_dtypes(include= 'number').columns
num_cols

Index(['capacity_mw', 'geopoint'], dtype='str')

In [22]:
#show data for each colmns with histogram and box plot
for col in num_cols:
    px.histogram(data_frame=df, x=col, title=col).show()
    px.box(data_frame=df, x=col, title=col).show()

In [23]:
#1 What is the global distribution of coal plant statuses?
status_counts= df['status'].value_counts()
px.pie(values=status_counts.values, names=status_counts.index, title='Global Distribution of Coal')

In [24]:
#2 Which countries have the highest coal power capacity?
country_capacity = df.groupby('country')['capacity_mw'].sum().sort_values(ascending=False).head(10)
px.bar(x=country_capacity.index, y=country_capacity.values,title='Top 10 Countries by Coal Power Capacity',text_auto=True, labels={'x':'Country', 'y':'Total Capacity (MW)',})

In [25]:
#3 Which regions rely most on coal energy
region_capacity = df.groupby('region')['capacity_mw'].sum().sort_values(ascending=False)
px.bar(x=region_capacity.index, y=region_capacity.values,title='Coal Power Capacity by Region',text_auto=True, labels={'x':'Region', 'y':'Total Capacity (MW)',})

In [26]:
#4 Which countries are retiring coal plants the fastest
retiring_plants = df[df['status'] == 'Retired']
retiring_capacity = retiring_plants.groupby('country')['capacity_mw'].sum().sort_values(ascending=False)
px.bar(x=retiring_capacity.index, y=retiring_capacity.values,title='Countries Retiring Coal Plants Fastest',text_auto=True, labels={'x':'Country', 'y':'Total Retiring Capacity (MW)',})

In [27]:
#5 What is the average coal plant capacity by country
country_avg_capacity = df.groupby('country')['capacity_mw'].mean().sort_values(ascending=False)
px.bar(x=country_avg_capacity.index, y=country_avg_capacity.values,title='Average Coal Plant Capacity by Country',text_auto=True, labels={'x':'Country', 'y':'Average Capacity (MW)',})

In [28]:
#6 Where are new coal plants under construction?
under_construction = df[df['status'] == 'Construction']
under_construction

,unit,plant,parent,url,capacity_mw,status,region,country,subnational_unit,geopoint
1,Unit 2,RÃ­o Turbio Power Station,Yacimientos CarbonÃ­feros De RÃ­o Turbio Sa,https://www.gem.wiki/R%C3%ADo_Turbio_power_sta...,120,Construction,Americas,Argentina,Santa Cruz,-51.54601
76,Unit 2,Han Seng Power Station,Han Seng Coal Mine Co [40.0%]; Guodian Kangnen...,https://www.gem.wiki/Han_Seng_power_station,132,Construction,Asia,Cambodia,Oddar Meanchey,14.23008
125,Unit 1,Antaibao Gangue Power Station,China Coal Energy Co Ltd [51.0%]; China Nation...,https://www.gem.wiki/Antaibao_Gangue_power_sta...,350,Construction,Asia,China,Shanxi,39.47126
134,Unit 3,Baitao Cogen Power Station,Huafon Chemical Co Ltd [77.6%]; Agricultural D...,https://www.gem.wiki/Baitao_cogen_power_station,60,Construction,Asia,China,Chongqing,29.59294
164,Unit 2,Ceec Chongzuo Power Station,China Energy Engineering Corp Ltd,https://www.gem.wiki/CEEC_Chongzuo_power_station,660,Construction,Asia,China,Guangxi,22.49487
...,...,...,...,...,...,...,...,...,...,...
10780,Unit 2,Krasnoyarsk Chp-3 Power Station,Siberian Coal Energy Company Jsc [99.9%],https://www.gem.wiki/Krasnoyarsk_CHP-3_power_s...,185,Construction,Europe,Russia,Krasnoyarsk,56.1088
10811,Unit 7,Severodvinsk-1 Power Station,Territorial Generating Company No 2 Ojsc,https://www.gem.wiki/Severodvinsk-1_power_station,30,Construction,Europe,Russia,Arkhangelsk,64.58103
10881,Unit 2,Samcheok Power Station,Nonghyup Bank [54.5%]; Posco Holdings Inc [34....,https://www.gem.wiki/Samcheok_power_station,1050,Construction,Asia,South Korea,Gangwon,37.40687
11283,Unit 1-2,Long Phu Power Centre,Petrovietnam Power Corporation Jsc,https://www.gem.wiki/Long_Phu_Power_Centre,600,Construction,Asia,Vietnam,Soc Trang,9.70894
11322,Unit 3,Zhongxin Power Station,Yuxia Zhongxin Coking Co,https://www.gem.wiki/ZhongXin_power_station,135,Construction,Africa,Zimbabwe,Matabeleland North,-18.08277

In [29]:
#How does operating vs retired capacity vary by region
capacity_by_region_status = df.groupby(['region', 'status'])['capacity_mw'].sum().reset_index()
capacity_by_region_status['percentage'] = (capacity_by_region_status.groupby('region')['capacity_mw'].transform(lambda x: x / x.sum()))
px.bar(capacity_by_region_status, x='region', y='percentage', color='status', title='Operating vs Retired Capacity by Region', text_auto='.2%')